include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_double_quotes: error
    missing_required_param: error
    missing_return: error
linter:
  rules:
    prefer_double_quotes: true
    avoid_print: false
